language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update && composer install

before_script:
  # Disable xdebug. NB: this should NOT be done for hhvm...
  - if [ $TRAVIS_PHP_VERSION != "hhvm" -a $TRAVIS_PHP_VERSION != "7.0" ]; then phpenv config-rm xdebug.ini; fi

  # TODO: we should set up an Apache instance inside the Travis VM and test it.
  # But it looks a bit complex, esp. as it seems that php has to be set up differently (cgi vs fpm) depending on version
  # So for now we just take an easy way out using a known remote server.
  # See: https://gist.github.com/roderik/3123962
  # See: http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis/apache_vhost /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default

  - sudo service apache2 restart

script:
  phpunit tests LOCALSERVER=localhost URI=/demo/server/server.php HTTPSSERVER=gggeek.ssl.altervista.org HTTPSURI=/sw/xmlrpc/demo/server/server.php NOPROXY=1
